/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ox_cs_JRDFox_store_ExtendedBuffer */

#ifndef _Included_uk_ac_ox_cs_JRDFox_store_ExtendedBuffer
#define _Included_uk_ac_ox_cs_JRDFox_store_ExtendedBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ox_cs_JRDFox_store_ExtendedBuffer
 * Method:    nGetBufferPtr
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_ox_cs_JRDFox_store_ExtendedBuffer_nGetBufferPtr
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
