/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ox_cs_JRDFox_store_Dictionary */

#ifndef _Included_uk_ac_ox_cs_JRDFox_store_Dictionary
#define _Included_uk_ac_ox_cs_JRDFox_store_Dictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ox_cs_JRDFox_store_Dictionary
 * Method:    nGetMaxResourceID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_ox_cs_JRDFox_store_Dictionary_nGetMaxResourceID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_Dictionary
 * Method:    nGetResources
 * Signature: (JJIIJIJJ)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ox_cs_JRDFox_store_Dictionary_nGetResources
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jint, jlong, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_Dictionary
 * Method:    nResolveResources
 * Signature: (J[J[Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_Dictionary_nResolveResources
  (JNIEnv *, jclass, jlong, jlongArray, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
