/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ox_cs_JRDFox_store_DataStore */

#ifndef _Included_uk_ac_ox_cs_JRDFox_store_DataStore
#define _Included_uk_ac_ox_cs_JRDFox_store_DataStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nCreate
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nCreate
  (JNIEnv *, jclass, jstring, jobjectArray, jlongArray);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nInitialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nInitialize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nSetNumberOfThreads
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nSetNumberOfThreads
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nAddTriples
 * Signature: (J[Ljava/lang/String;[III)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nAddTriples
  (JNIEnv *, jclass, jlong, jobjectArray, jintArray, jint, jint);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nAddTriplesByResourceIDs
 * Signature: (J[JII)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nAddTriplesByResourceIDs
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nImportFiles
 * Signature: (J[Ljava/lang/String;IZZ)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nImportFiles
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jboolean, jboolean);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nImportText
 * Signature: (JLjava/lang/String;IZZ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nImportText
  (JNIEnv *, jclass, jlong, jstring, jint, jboolean, jboolean, jobjectArray);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nExport
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nExport
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nApplyRules
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nApplyRules
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nUpdateStatistics
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nUpdateStatistics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nMakeFactsExplicit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nMakeFactsExplicit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nClearRulesAndMakeFactsExplicit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nClearRulesAndMakeFactsExplicit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nSave
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nSave
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nLoad
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nLoad
  (JNIEnv *, jclass, jstring, jlongArray);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_DataStore
 * Method:    nDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_DataStore_nDispose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
