/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ox_cs_JRDFox_store_TupleIterator */

#ifndef _Included_uk_ac_ox_cs_JRDFox_store_TupleIterator
#define _Included_uk_ac_ox_cs_JRDFox_store_TupleIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ox_cs_JRDFox_store_TupleIterator
 * Method:    nCompileQuery
 * Signature: (JLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_ox_cs_JRDFox_store_TupleIterator_nCompileQuery
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jobjectArray, jintArray);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_TupleIterator
 * Method:    nOpen
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ox_cs_JRDFox_store_TupleIterator_nOpen
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_TupleIterator
 * Method:    nAdvance
 * Signature: (JIJJ)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ox_cs_JRDFox_store_TupleIterator_nAdvance
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_TupleIterator
 * Method:    nGetResources
 * Signature: (JJIIJIJJ)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_ox_cs_JRDFox_store_TupleIterator_nGetResources
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jlong, jint, jlong, jlong);

/*
 * Class:     uk_ac_ox_cs_JRDFox_store_TupleIterator
 * Method:    nDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ox_cs_JRDFox_store_TupleIterator_nDispose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
